from typing import Iterable

class ReplayMemory:
    def __init__(self, capacity: int) -> None: ...
    def get(self, index: int) -> object: ...
    def push(self, item: object): ...
    def push_items(self, items: Iterable[object]): ...
    @property
    def is_full(self) -> bool: ...
    @property
    def is_empty(self) -> bool: ...
    def __getitem__(self, idx: int) -> object: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
